# PowerShell script to fix encoding issues in TypeScript files

Write-Host "Fixing encoding issues in TypeScript files..."

# Get all TypeScript files
$tsFiles = Get-ChildItem -Path "src" -Recurse -Filter "*.ts" | Where-Object { $_.FullName -notlike "*backup*" }

foreach ($file in $tsFiles) {
    Write-Host "Processing: $($file.FullName)"
    
    try {
        # Read file content with UTF-8 encoding
        $content = Get-Content $file.FullName -Encoding UTF8 -Raw
        
        # Fix common encoding issues
        $content = $content -replace "定�?", "定义"
        $content = $content -replace "类�?", "类型"
        $content = $content -replace "接�?", "接口"
        $content = $content -replace "方�?", "方法"
        $content = $content -replace "属�?", "属性"
        $content = $content -replace "参�?", "参数"
        $content = $content -replace "返�?", "返回"
        $content = $content -replace "配�?", "配置"
        $content = $content -replace "系�?", "系统"
        $content = $content -replace "管�?", "管理"
        $content = $content -replace "处�?", "处理"
        $content = $content -replace "错�?", "错误"
        $content = $content -replace "日�?", "日志"
        $content = $content -replace "记�?", "记录"
        $content = $content -replace "存�?", "存储"
        $content = $content -replace "缓�?", "缓存"
        $content = $content -replace "队�?", "队列"
        $content = $content -replace "线�?", "线程"
        $content = $content -replace "进�?", "进程"
        $content = $content -replace "服�?", "服务"
        $content = $content -replace "客户�?", "客户端"
        $content = $content -replace "服务�?", "服务器"
        $content = $content -replace "网�?", "网络"
        $content = $content -replace "连�?", "连接"
        $content = $content -replace "请�?", "请求"
        $content = $content -replace "响�?", "响应"
        $content = $content -replace "数据�?", "数据库"
        $content = $content -replace "查�?", "查询"
        $content = $content -replace "更�?", "更新"
        $content = $content -replace "删�?", "删除"
        $content = $content -replace "插�?", "插入"
        $content = $content -replace "创�?", "创建"
        $content = $content -replace "初始�?", "初始化"
        $content = $content -replace "启�?", "启动"
        $content = $content -replace "停�?", "停止"
        $content = $content -replace "重�?", "重启"
        $content = $content -replace "监�?", "监控"
        $content = $content -replace "检�?", "检查"
        $content = $content -replace "验�?", "验证"
        $content = $content -replace "测�?", "测试"
        $content = $content -replace "调�?", "调试"
        $content = $content -replace "优�?", "优化"
        $content = $content -replace "性�?", "性能"
        $content = $content -replace "安全�?", "安全性"
        $content = $content -replace "权�?", "权限"
        $content = $content -replace "认�?", "认证"
        $content = $content -replace "授�?", "授权"
        $content = $content -replace "加�?", "加密"
        $content = $content -replace "解�?", "解密"
        $content = $content -replace "签�?", "签名"
        $content = $content -replace "证�?", "证书"
        $content = $content -replace "密�?", "密钥"
        $content = $content -replace "令�?", "令牌"
        $content = $content -replace "会�?", "会话"
        $content = $content -replace "状�?", "状态"
        $content = $content -replace "模�?", "模式"
        $content = $content -replace "模�?", "模块"
        $content = $content -replace "组�?", "组件"
        $content = $content -replace "插�?", "插件"
        $content = $content -replace "扩�?", "扩展"
        $content = $content -replace "接�?", "接口"
        $content = $content -replace "实�?", "实现"
        $content = $content -replace "继�?", "继承"
        $content = $content -replace "封�?", "封装"
        $content = $content -replace "多�?", "多态"
        $content = $content -replace "抽�?", "抽象"
        $content = $content -replace "具�?", "具体"
        $content = $content -replace "通�?", "通用"
        $content = $content -replace "特�?", "特定"
        $content = $content -replace "默�?", "默认"
        $content = $content -replace "自定�?", "自定义"
        $content = $content -replace "标�?", "标准"
        $content = $content -replace "规�?", "规范"
        $content = $content -replace "协�?", "协议"
        $content = $content -replace "格�?", "格式"
        $content = $content -replace "版�?", "版本"
        $content = $content -replace "更�?", "更新"
        $content = $content -replace "升�?", "升级"
        $content = $content -replace "迁�?", "迁移"
        $content = $content -replace "备�?", "备份"
        $content = $content -replace "恢�?", "恢复"
        $content = $content -replace "同�?", "同步"
        $content = $content -replace "异�?", "异步"
        $content = $content -replace "并�?", "并发"
        $content = $content -replace "串�?", "串行"
        $content = $content -replace "队�?", "队列"
        $content = $content -replace "堆�?", "堆栈"
        $content = $content -replace "缓冲�?", "缓冲区"
        $content = $content -replace "内存�?", "内存池"
        $content = $content -replace "对象�?", "对象池"
        $content = $content -replace "连接�?", "连接池"
        $content = $content -replace "线程�?", "线程池"
        $content = $content -replace "资源�?", "资源池"
        $content = $content -replace "算�?", "算法"
        $content = $content -replace "数据结�?", "数据结构"
        $content = $content -replace "设计模�?", "设计模式"
        $content = $content -replace "架构模�?", "架构模式"
        $content = $content -replace "编程模�?", "编程模式"
        $content = $content -replace "开发模�?", "开发模式"
        $content = $content -replace "部署模�?", "部署模式"
        $content = $content -replace "运行模�?", "运行模式"
        $content = $content -replace "工作模�?", "工作模式"
        $content = $content -replace "操作模�?", "操作模式"
        $content = $content -replace "访问模�?", "访问模式"
        $content = $content -replace "存储模�?", "存储模式"
        $content = $content -replace "传输模�?", "传输模式"
        $content = $content -replace "通信模�?", "通信模式"
        $content = $content -replace "交互模�?", "交互模式"
        $content = $content -replace "界面模�?", "界面模式"
        $content = $content -replace "显示模�?", "显示模式"
        $content = $content -replace "输入模�?", "输入模式"
        $content = $content -replace "输出模�?", "输出模式"
        $content = $content -replace "处理模�?", "处理模式"
        $content = $content -replace "执行模�?", "执行模式"
        $content = $content -replace "调度模�?", "调度模式"
        $content = $content -replace "管理模�?", "管理模式"
        $content = $content -replace "控制模�?", "控制模式"
        $content = $content -replace "监控模�?", "监控模式"
        $content = $content -replace "日志模�?", "日志模式"
        $content = $content -replace "错误模�?", "错误模式"
        $content = $content -replace "异常模�?", "异常模式"
        $content = $content -replace "恢复模�?", "恢复模式"
        $content = $content -replace "容错模�?", "容错模式"
        $content = $content -replace "安全模�?", "安全模式"
        $content = $content -replace "调试模�?", "调试模式"
        $content = $content -replace "测试模�?", "测试模式"
        $content = $content -replace "开发模�?", "开发模式"
        $content = $content -replace "生产模�?", "生产模式"
        $content = $content -replace "维护模�?", "维护模式"
        
        # Write back to file with UTF-8 encoding
        $content | Set-Content $file.FullName -Encoding UTF8 -NoNewline
        
        Write-Host "Fixed: $($file.FullName)" -ForegroundColor Green
    }
    catch {
        Write-Host "Error processing $($file.FullName): $($_.Exception.Message)" -ForegroundColor Red
    }
}

Write-Host "Encoding fix completed!" -ForegroundColor Green
